# Misc vars
export TERM=xterm-256color
export GIT_EDITOR=nvim
export ANSIBLE_NOCOWS=1
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
#https://wiki.archlinux.org/index.php/Xmonad#LibreOffice_-_focus_flicking_between_main_window_and_dialog
export SAL_USE_VCLPLUGIN=gen lowriter

# Lock screen only on one screen
export XSECURELOCK_SINGLE_AUTH_WINDOW=1

# Avoid alacritty to scale font on DPI
export WINIT_X11_SCALE_FACTOR=1

export PATH="$HOME/.bin:$HOME/.krew/bin:$HOME/.local/bin:$HOME/.local/goenv/bin:$HOME/.local/goenv-data/shims:$PATH"
