# Misc vars
export TERM=xterm-256color
export GIT_EDITOR=nvim
export ANSIBLE_NOCOWS=1
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export DOCKER_ID_USER=nmaupu
#https://wiki.archlinux.org/index.php/Xmonad#LibreOffice_-_focus_flicking_between_main_window_and_dialog
export SAL_USE_VCLPLUGIN=gen lowriter

export PATH="$HOME/.bin:$HOME/.krew/bin:$HOME/.local/bin:$HOME/.local/tfenv/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/downloads/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/downloads/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/downloads/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/downloads/google-cloud-sdk/completion.zsh.inc"; fi
