# Powerlevel10k is configured using ~/.p10k.zsh

# History
export HISTFILE=/home/nmaupu/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS

export EDITOR=nvim

# Do not sighup background jobs
setopt NO_HUP
setopt NO_CHECK_JOBS

# Enable bash comment style with dash character
setopt interactivecomments

# Misc bindings
bindkey "^[Oc" forward-word
bindkey "^[Od" backward-word
bindkey "\^U"  backward-kill-line
bindkey "^[m"  copy-earlier-word

if [ -f ~/.ssh/config ]; then
  h=()
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config*)"}:#Host *}#Host }:#*[*? ]*})
  if [[ $#h -gt 0 ]]; then
    zstyle ':completion:*:ssh:*' hosts $h
    zstyle ':completion:*:scp:*' hosts $h
    zstyle ':completion:*:rsync:*' hosts $h
    zstyle ':completion:*:slogin:*' hosts $h
    zstyle ':completion:*:pssh:*' hosts $h
    zstyle ':completion:*:cssh:*' hosts $h
  fi
fi

autoload -Uz compinit && compinit

# Plugins and themes
source "${ZDOTDIR:-$HOME}/.antidote/antidote.zsh"
antidote load ${ZDOTDIR:-$HOME}/.zsh_plugins.txt

# Fixing non working git-completion because of missing functions
# Those functions are defined in git-minimal package (guix) under the following paths:
# /gnu/store/xxx-git-minimal-xxx/share/zsh/site-functions/_git
# and
# /gnu/store/xxx-git-minimal-xxx/etc/bash_completion.d/git
zstyle ':completion:*:*:git:*' script "${ZDOTDIR:-$HOME}/.git-completion.bash"
_git_completion_loader(){
  source "${ZDOTDIR:-$HOME}/.git-completion.zsh"
}
compdef _git_completion_loader git
##


# FZF config
_gen_fzf_default_opts() {
  local base03="234"
  local base02="235"
  local base01="240"
  local base00="241"
  local base0="244"
  local base1="245"
  local base2="254"
  local base3="230"
  local yellow="136"
  local orange="166"
  local red="160"
  local magenta="125"
  local violet="61"
  local blue="33"
  local cyan="37"
  local green="64"

  # Solarized Dark color scheme for fzf
  export FZF_DEFAULT_OPTS="
    --no-height --border --exact
    --color fg:-1,bg:-1,hl:$blue,fg+:$base2,bg+:$base02,hl+:$blue
    --color info:$yellow,prompt:$yellow,pointer:$base3,marker:$base3,spinner:$yellow
  "

}
_gen_fzf_default_opts
source <(fzf --zsh)

# Custom aliases
alias test_term_colors="wget -O - https://raw.githubusercontent.com/robertknight/konsole/master/tests/color-spaces.pl | perl; \
  curl -s https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash"
alias vim="nvim"
alias vi="nvim"
alias s="nvim + ~/.scratchpad"
alias history="fc -il 1"
alias emacs="$HOME/.local/bin/doom-emacs"
alias doom="$HOME/.config/emacs/bin/doom"
alias k="kubectl"
alias us="xkbcomp -I$XDG_CONFIG_HOME/xkb $XDG_CONFIG_HOME/xkb/qwertyfr.xkb $DISPLAY 2>/dev/null; xmodmap -e 'keysym Escape = Escape asciitilde Escape'"

# Kubernetes - change context
kcs() {
  local new_context
  if [ "$1" = '-' ]; then
    new_context = '-'
  else
    new_context=$(kubectl config get-contexts -o=name | fzf -0 -1 --tac -q "${1:-""}")
  fi

  kubectl config use-context "${new_context}"
}

# Kubernetes - change current namespace
kns() {
  local new_context
  if [ "$1" = '-' ]; then
    new_ns = '-'
  else
    new_ns=$(kubectl get ns | awk 'NR>2{print $1}'| fzf -0 -1 --tac)
  fi

  kubectl config set-context $(kubectl config current-context) --namespace="${new_ns}"
}

# Custom and private configs
if [ -d "${ZDOTDIR:-$HOME}/.zshrc.d" ]; then
  find "${ZDOTDIR:-$HOME}/.zshrc.d" -type f | while read -r file; do
    source "${file}"
  done
fi

# kube configs
if [ -d "$HOME/.kube/conf.d" ]; then
  find "$HOME/.kube/conf.d" -type f | while read -r file; do
    KUBECONFIG="${KUBECONFIG}:${file}"
  done
  export KUBECONFIG
fi

# Autosuggestions default color is the same as the background color...
# Changing it to dark gray
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
[[ ! -f "${ZDOTDIR:-$HOME}/.p10k.zsh" ]] || . "${ZDOTDIR:-$HOME}/.p10k.zsh"

# Google Cloud gnu store install path
GCLOUD_DIR=$(dirname $(dirname $(realpath /home/nmaupu/.guix-home/profile/bin/gcloud)))
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$GCLOUD_DIR/path.zsh.inc" ]; then . "$GCLOUD_DIR/path.zsh.inc"; fi
# The next line enables shell command completion for gcloud.
if [ -f "$GCLOUD_DIR/completion.zsh.inc" ]; then . "$GCLOUD_DIR/completion.zsh.inc"; fi

# Fix go run / go build not setting the correct RPATH
go() {
  CC=$HOME/.guix-home/profile/bin/gcc
  CGO_RPATH=$HOME/.guix-profile/lib
  if [ "${CGO_ENABLED:-1}" = "1" ]; then
    CGO_ENABLED=1 CC="$CC" CGO_LDFLAGS="-Wl,-rpath=$CGO_RPATH${CGO_LDFLAGS:+ $CGO_LDFLAGS}" \
    GOFLAGS="-ldflags=-linkmode=external${GOFLAGS:+ ${GOFLAGS}}" \
    command /usr/bin/env go "$@"
  else
    command /usr/bin/env go "$@"
  fi
}
